### PR TITLE
Dbi tests

### PR DESCRIPTION
**Pull request by pingwiniasty**
DBI Tests. Work in progress...

### CODE REVIEW

**Comment by pingwiniasty** [comment]
Be patient, I'm working on it :D

**Comment by pingwiniasty** [comment]
There are no all tests, but I want to help you with new web or maybe we can focus on AddObject.

**Comment by jarlah** [comment]
CI problem is unrelated

**Comment by pingwiniasty** [comment]
Sorry, I'm still trying to get to know this code. I will add new tests when needed

**Comment by jarlah** [comment]
@pingwiniasty i think its good enough for now. I think the most pressing issue is AddObject, but when i make a shell for graphql server, you could implement the resolvers for the different models, like unittype, jobs etc.

**Pull request merged**
