### PR TITLE
refactor to strategy pattern (part 1 of Restructure All The Things :D )

### PR DESCRIPTION
**Pull request by jarlah**
Make it easier to reason about what happens in the tr069 server.

This change will make it alot easier to add support for new methods. 

It will also be easier to test. 

And it will be easier to understand and maintain. Hurra 🙌 

These things have been done:

1. Removing annoyingly complicated logic to process, decide and respond
2. Replacing with strategy implementations that is more loosely coupled (great) and more readable
3. Provisioning method is now an enum and the abbreviation is a part of it.

### CODE REVIEW

**Comment by jarlah** [comment]
code climate complains about existing problems .. meh

**Comment by pingwiniasty** [comment]
Cool, it's looks very clean :D 
But in next step, I suggest to clean up incomprehensible methods names like `putPvs`
And why there is 4 classes in one file? `tr069/methods/decision/GetParameterValuesDecisionStrategy.java`

**Comment by jarlah** [comment]
@pingwiniasty there is four classes in one file now because the logic belongs to this decision class. A solution would be to make a sub package. For that decision class and its companion classes

**Comment by jarlah** [comment]
Or Just make a utils package. But i would like to avoid giving the assumption that these classes can or should be used by other  classes

**Comment by jarlah** [comment]
@pingwiniasty moved the three other classes to a package called GetParameterValues (yes, i know, uppercase package, but this is something that relates to this specific soap method, and i dont want to use like gpv for package name...

**Comment by jarlah** [comment]
oh and btw .. the SessionData class is horrific ... it should just be a simple POJO class containing session data but it contains advanced logic. I will work on this later.

**Comment by jarlah** [comment]
Finished. Wont do any more now .. waiting for approval/denial ;) @pingwiniasty

**Comment by jarlah** [comment]
I miiight have removed some pretty printing. But i suggest to work on it iteratively. When you have approved or if then we merge. Then i create issue to investigate if pretty print of xml can be added back

**Pull request merged**
