### PR TITLE
Update application.properties

### PR DESCRIPTION
**Pull request by jpVm5jYYRE1VIKL**
Nginx container configuration now try connect to port 8080. So last night patch bit break access to web project.

### CODE REVIEW

**Comment by jarlah** [comment]
I am struggling to see whats the problem and where it comes from.

Running docker? I might have introduced some changes to .env file, and even docker-compose.yml file. 

The port defined in the application.properties is correct for installing via shell scripts and deb files. Each deb file has its own port on the system.

**Comment by jpVm5jYYRE1VIKL** [comment]
yes i rinning docker. 
in your nginx docker image configured :
```
    location /tr069/ {
      proxy_set_header        X-Real-IP       $remote_addr;
      proxy_pass http://tr069:8080/tr069/;
    }
    location /web/ {
      proxy_pass http://web:8080/web/;
    }
    location /monitor/ {
      proxy_pass http://monitor:8080/monitor/;
    }
    location /webservice/ {
      proxy_pass http://webservice:8080/webservice/;
    }
    location /syslog/ {
      proxy_pass http://syslog:8080/syslog/;
    }
    location /core/ {
      proxy_pass http://core:8080/core/;
    }
    location /stun/ {
      proxy_pass http://stun:8080/stun/;
    }
```

so i changed application.properties to be compatible with nginx container

**Comment by jarlah** [comment]
Its not correct way to handle this problem, if its a problem at all. Its overridden by .env file. In .env file it says SERVER_PORT=8080.
If the .env file is not overriding server port, then that is another more important matter that must be solved differently.

**Comment by jarlah** [comment]
I suppose that docker-compose -p freeacs restart is not the best to use. use down and up -d

**Pull request closed without merging**
